server:
  port: 7070
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/education
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
